name: test
on: pull_request
jobs:
  test:
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
        eslint: [7, 8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install
          npm install eslint@${{ matrix.eslint }}
          npm run lint
          npm run test
        continue-on-error: ${{ matrix.eslint == '8' }}
