name: test

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize
        uses: ./.github/actions/restore-node

      - name: Run Lint
        run: npm run lint

      - name: Run Test
        run: npm run test
