name: test

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        eslint: [7, 8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version

      - name: Use ESLint ${{ matrix.eslint }}
        run: npm install eslint@${{ matrix.eslint }}

      - run: |
          npm install --silent
          npm run lint
          npm run test
